// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PeiIntegrationServiceApiTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("PeiIntegrationService Tests")]
    public partial class PeiIntegrationServiceTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "PeiIntegrationService.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "PeiIntegrationService Tests", "API Tests for PEI Integration Service. To Test on Local use localhost in place of" +
                    " Azure QA Environment.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get Request with Valid inputs")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("pei")]
        public virtual void GetRequestWithValidInputs()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "regression",
                    "pei"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Request with Valid inputs", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given("user sends get request to \'Azure QA Environment\' peis endpoint", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.Then("response is all ok with response code as \'OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 9
 testRunner.And("response header contains rpt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.And("response body contains pei with description, retrievalStatus, retrievalRequestedT" +
                        "imestamp", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get Request with various invalid inputs")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("pei")]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9071", "https://maps.com", "askdj902139012ekasdlasda", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "OK", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9072", "https://maps.com", "askdj902139012ekasdlasdb", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.netxxx", "InternalServerError", null)]
        [NUnit.Framework.TestCaseAttribute("11111111-1111-1111-1111-111111111173", "https://maps.com", "askdj902139012ekasdlasdc", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "qwertyuoip", "", "BadRequest", null)]
        [NUnit.Framework.TestCaseAttribute("11111111-1111-1111-1111-111111111174", "https://maps.com", "askdj902139012ekasdlasdd", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "qwertyuoipxxx", "https://cdaserviceemulator.azurewebsites.net", "OK", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9075", "https://maps.com", "askdj902139012ekasdlasde", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "", "https://cdaserviceemulator.azurewebsites.net", "BadRequest", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9076", "https://maps.com", "askdj902139012ekasdlasda", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "BadRequest", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9077", "https://maps.com", "askdj902139012ekasdlasda", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "ownerxxx", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "BadRequest", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9078", "https://maps.com", "askdj902139012ekasdlasda", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "uma_protection", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "BadRequest", null)]
        [NUnit.Framework.TestCaseAttribute("11111111-1111-1111-1111-111111111179", "https://maps.com", "askdj902139012ekasdlasdf", "", "owner", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "Unauthorized", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9080", "https://maps.com", "askdj902139012ekasdlasdm", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHIxxx", "owner", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "OK", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9081", "https://maps.com", "", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "Unauthorized", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9082", "https://maps.com", "askdj902139012ekasdlasdxxx", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "OK", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9083", "", "askdj902139012ekasdlasdi", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "Unauthorized", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9084", "https://maps.comxxx", "askdj902139012ekasdlasdh", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "OK", null)]
        [NUnit.Framework.TestCaseAttribute("", "https://maps.com", "askdj902139012ekasdlasdj", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "Unauthorized", null)]
        [NUnit.Framework.TestCaseAttribute("cd0e4fdc-8586-4483-9899-17dd85af9086xxx", "https://maps.com", "askdj902139012ekasdlasdk", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3" +
            "Nzk2Mzh9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI", "owner", "qwertyuoip", "https://cdaserviceemulator.azurewebsites.net", "Unauthorized", null)]
        public virtual void GetRequestWithVariousInvalidInputs(string cdaUserGuid, string iss, string userSessionId, string rpt, string scope, string requestId, string peiBaseUrl, string statusCode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "smoke",
                    "regression",
                    "pei"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("cdaUserGuid", cdaUserGuid);
            argumentsOfScenario.Add("iss", iss);
            argumentsOfScenario.Add("userSessionId", userSessionId);
            argumentsOfScenario.Add("rpt", rpt);
            argumentsOfScenario.Add("scope", scope);
            argumentsOfScenario.Add("requestId", requestId);
            argumentsOfScenario.Add("peiBaseUrl", peiBaseUrl);
            argumentsOfScenario.Add("StatusCode", statusCode);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Request with various invalid inputs", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 15
 testRunner.Given(string.Format("get request sent to \'Azure QA Environment\' with headers as \'{0}\' for guid \'{1}\' f" +
                            "or iss \'{2}\' for sessionid \'{3}\' for authorisation with params as \'{4}\' request " +
                            "body having \'{5}\' for request id \'{6}\' for request url", cdaUserGuid, iss, userSessionId, rpt, scope, requestId, peiBaseUrl), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 16
 testRunner.Then(string.Format("response is all ok with response code as \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
