<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>PensionsDataService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MhpdCommon" Version="2.0.58" />
        <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
        <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.43.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\swagger\v1" />
    </ItemGroup>
    
    <Target Name="OpenAPI" AfterTargets="Build" Condition="$(Configuration)=='Debug'">
        <Exec Command="dotnet swagger tofile --output ./wwwroot/swagger/v1/pension-data.json $(OutputPath)$(AssemblyName).dll v1" WorkingDirectory="$(ProjectDir)" />
    </Target>
</Project>
