<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>PensionsDataService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MhpdCommon" Version="3.0.1" />
        <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\swagger\v1" />
    </ItemGroup>
	
	<Target Name="OpenAPI" AfterTargets="Build" Condition="$(Configuration)=='Debug'">
		<Exec Command="dotnet swagger tofile --output ./wwwroot/swagger/v1/pension-data.json $(OutputPath)$(AssemblyName).dll v1" WorkingDirectory="$(ProjectDir)" />
	</Target>
</Project>
